#!/bin/sh
# /etc/hotplug.d/iface/99-modem-led
# Modem LED control based on interface status

case "$ACTION:$INTERFACE" in
    ifup:modem)
        ledcontrol blue:wan on
        logger -t modem-led "Modem UP - Blue LED ON"
        ;;
    ifdown:modem)
        ledcontrol blue:wan off
        logger -t modem-led "Modem DOWN - Blue LED OFF"
        ;;
esac
